[features]
seeds = false
skip-lint = false

[programs.localnet]
hackaton = "5LFMvXhLFNwtpiqFzmm2ZgYMBZ3ycYenvKqdJUCr4wpe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/acammm/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
